# Generated by Django 2.0.5 on 2018-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.IntegerField()),
                ('line_code', models.IntegerField()),
                ('issues_created', models.IntegerField()),
                ('issues_closed', models.IntegerField()),
            ],
        ),
    ]
