# Generated by Django 2.0.5 on 2018-06-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='commits_db_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='issues_db_updated',
            field=models.IntegerField(default=0),
        ),
    ]
