# Generated by Django 2.0.5 on 2018-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180621_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='commits_db_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='issues_db_updated',
            field=models.BooleanField(default=False),
        ),
    ]
