# Generated by Django 2.0.5 on 2018-06-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180623_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='paired',
        ),
    ]
