# Generated by Django 2.0.5 on 2018-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_commit_paired'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
