# Generated by Django 2.0.5 on 2018-06-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_commit_paired'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_by', models.BigIntegerField()),
                ('closed_by', models.BigIntegerField(null=True)),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Repository')),
            ],
        ),
    ]
