# Generated by Django 2.0.5 on 2018-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='pulls_db_updated',
            field=models.BooleanField(default=False),
        ),
    ]
