# Generated by Django 2.0.5 on 2018-06-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_repository_pulls_db_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='closed_by',
        ),
    ]
