# Generated by Django 2.0.5 on 2018-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_pullrequest_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='closed_by',
            field=models.BigIntegerField(null=True),
        ),
    ]
