# Generated by Django 2.0.5 on 2018-06-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pullrequest_closed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='closed_by',
        ),
    ]
